### ISSUE TITLE
latest versions?

### ISSUE THREAD

**Issue by gearcapitan** [nicolaswehmeyer/tufin-backup-wizard#1]
Are there problems if I run the script in TOS R18-1 and TufinOS 2.16?

**Comment by asainsbury** [comment]
We are running this script on 18.1 2.15 without any issues.

**Comment by gearcapitan** [comment]
thanx!

**Comment by asainsbury** [comment]
Just be mindful of the path you supply to do the backups, if you miss the trailing "/" then it puts the files into the higher level directory.

I.E. /backup will go into / 
You would need to supply /backup/ for it to take effect fully. 

I submitted a PR with a fix, but I think the maintainer is busy.

**Comment by nicolaswehmeyer** [comment]
Hey guys, I have just seen this. I updated the latest versions as well as fixing the path issue. Thanks to @asainsbury for answering questions here!
