### ISSUE TITLE
Backup path doesn't check for the trailing /

### ISSUE THREAD

**Issue by asainsbury** [nicolaswehmeyer/tufin-backup-wizard#4]
We run this bit of code at work (pretty neat, and thanks!) but I noticed that the last person to run the wizard forgot to supply the full path, and missed the trailing slash. The config creates the path which was entered by the user, and unfortunately when the script runs the backup, it skips the incorrect path and pushed the backup file into /root/ which caused a problem when the cleanup routine fails to find any files in the configured backup path. All the files get pushed into /root.

I submitted a PR with a bit of error checking.

Thanks,
/Andy

**Comment by nicolaswehmeyer** [comment]
Hey @asainsbury ! Thank you for mentioning this, although this was a while ago, I got more and more feedback lately and the script is heavily in use. So I just took your PR and merged it into master! Many thanks for this, this is definitely useful!:-) I will close this issue now.
